# fly.toml file generated for tailproxy on 2022-11-18T13:19:52+08:00

app = "tailproxy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
