# fly.toml app configuration file generated for tailsocks on 2023-05-05T14:45:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tailsocks"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80
